In [1]:
import sys
import torch
MODULEPATH="../../"
sys.path.append(MODULEPATH)
sys.path.append('../')

from critical_points.torch_critical_point_finder import find_critical_points_torch, save_critical_points_to_csv
from test_schwefel.schwefel_function_nnmodule import Schwefel3D, schwefel_loss, schwefel3D_numpy  # your existing module


In [2]:
# Set parameters
BOUNDS = (0.0, 1.0)
DIM = 3
ATTEMPTS = 64
MIN_DISTANCE = 0.01


In [3]:
# Run search
minima, maxima, saddles = find_critical_points_torch(
    model_class=Schwefel3D,
    loss_func=schwefel_loss,
    input = [],             # placeholder model input for compatibility (Schwefel model has no model input)
    bounds=BOUNDS,
    dimension=DIM,
    num_attempts=ATTEMPTS,
    min_distance=MIN_DISTANCE,
    device="cpu",
    lr=1e-3,
    steps=1400
)

Attempt 1/64: starting point [0.99751333 0.10436639 0.82297882]
[0.82437602 0.03455281 0.82437515] Reject: False
Attempt 2/64: starting point [0.22268048 0.73696758 0.44764793]
[0.34180738 0.8243736  0.34181119] Reject: False
Attempt 3/64: starting point [0.48094171 0.35632647 0.51044139]
[0.34181075 0.34181056 0.34181158] Reject: False
Attempt 4/64: starting point [0.73929411 0.98886296 0.13519257]
[0.8243759  0.82437533 0.03455275] Reject: False
Attempt 5/64: starting point [0.54678582 0.46132329 0.2819464 ]
[0.34180982 0.34180642 0.34181076] Reject: True
Attempt 6/64: starting point [0.30332528 0.8126126  0.9066477 ]
[0.34181069 0.82437502 0.82437636] Reject: False
Attempt 7/64: starting point [0.06142913 0.21714397 0.09447237]
[0.03455004 0.34180656 0.03455045] Reject: False
Attempt 8/64: starting point [0.78865527 0.56849041 0.71912985]
[0.8243751  0.82437518 0.82437655] Reject: False
Attempt 9/64: starting point [0.85367705 0.28965247 0.01324134]
[0.82437413 0.3418057  0.03455071

In [4]:
# Save to CSV
results_df = save_critical_points_to_csv(minima, saddles, dimension=DIM, filename="critical_points_schwefel_torch3D.csv")
display(results_df.head())

Saved critical_points_schwefel_torch3D.csv


,x1,x2,x3,f_value,type,index
0,0.824376,0.034553,0.824375,-0.482618,minimum,0
1,0.341807,0.824374,0.341811,-0.403686,minimum,0
2,0.341811,0.341811,0.341812,-0.186547,minimum,0
3,0.824376,0.824375,0.034553,-0.482618,minimum,0
4,0.341811,0.824375,0.824376,-0.620826,minimum,0
