In [1]:
import sys
import torch
MODULEPATH="../../"
sys.path.append(MODULEPATH)
sys.path.append('../')

from critical_points.torch_critical_point_finder import find_critical_points_torch, save_critical_points_to_csv
from test_schwefel.schwefel_function_nnmodule import Schwefel4D, schwefel_loss, schwefel4D_numpy  # your existing module

In [2]:
# Set parameters
BOUNDS = (0.0, 1.0)
DIM = 4
ATTEMPTS = 64
MIN_DISTANCE = 0.01


In [3]:
# Run search
minima, maxima, saddles = find_critical_points_torch(
    model_class=Schwefel4D,
    loss_func=schwefel_loss,
    input = [],             # placeholder model input for compatibility (Schwefel model has no model input)
    bounds=BOUNDS,
    dimension=DIM,
    num_attempts=ATTEMPTS,
    min_distance=MIN_DISTANCE,
    device="cpu",
    lr=0.01,
    steps=400
)

Attempt 1/64: starting point [0.99751333 0.10436639 0.82297882 0.41943216]
[0.82437546 0.03455089 0.82437499 0.34181005] Reject: False
Attempt 2/64: starting point [0.45270089 0.83806729 0.07327047 0.61616995]
[0.34180503 0.82437313 0.03454696 0.82436525] Reject: False
Attempt 3/64: starting point [0.21818378 0.35022259 0.69792678 0.17396588]
[0.34181134 0.34180952 0.82437579 0.34181164] Reject: False
Attempt 4/64: starting point [0.73199227 0.58429702 0.44830628 0.85320571]
[0.82437417 0.8243759  0.34180938 0.82437425] Reject: False
Attempt 5/64: starting point [0.58623255 0.39030191 0.15491497 0.90961866]
[0.82437253 0.34180443 0.0345524  0.82436593] Reject: False
Attempt 6/64: starting point [0.10416282 0.68686688 0.90539401 0.11814042]
[0.0345517  0.82437606 0.82437528 0.03455204] Reject: False
Attempt 7/64: starting point [0.36945694 0.12874209 0.27998973 0.68374849]
[0.34180939 0.03455385 0.34181001 0.82437659] Reject: False
Attempt 8/64: starting point [0.82100719 0.92494866 0.5

In [4]:
# Save to CSV
results_df = save_critical_points_to_csv(minima, saddles, dimension=DIM, filename="critical_points_schwefel_torch4D.csv")
display(results_df.head())

Saved critical_points_schwefel_torch4D.csv


,x1,x2,x3,x4,f_value,type,index
0,0.824375,0.034551,0.824375,0.341810,-0.684461,minimum,0
1,0.341805,0.824373,0.034547,0.824365,-0.684461,minimum,0
2,0.341811,0.341810,0.824376,0.341812,-0.605530,minimum,0
3,0.824374,0.824376,0.341809,0.824374,-1.039809,minimum,0
4,0.824373,0.341804,0.034552,0.824366,-0.684461,minimum,0
